### ISSUE TITLE
Ctrl-Tab

### ISSUE THREAD

**Issue by golavr** [tshino/vscode-kb-macro#119]
Excellent extension, it has one problem though, Ctrl-Tab will stop working correctly after installation.

**Comment by tshino** [comment]
Thank you for reporting!

I appreciate your letting me know the problem.
I confirm that the behavior of `Ctrl+Tab` becomes slightly different with this extension installed.
(I tested only with VS Code 1.68.0 on Windows 10.)

### The issue
Clarifying the issue, the original behavior is:

1. When you press `Ctrl+Tab`, the Quick Open menu appears on top of the window and the second item has the focus.
2. Then if you immediately release `Ctrl+Tab`, the tab with the focus will open.

But with this extension installed, when you release the key the menu stays open and the tab doesn't change. You have to click or press Enter/Space to open the focused item.

![image](https://user-images.githubusercontent.com/732920/173214684-fef85b89-a5c2-4cc8-b79f-a9cf821e1e96.png)

Does this describe your issue correctly?
Anyway, I will try to find the cause and hopefully fix it.
Thank you.

**Comment by tshino** [comment]
Hi,
Though I don't see any cause or mechanism that makes this happen, I think I have fixed this issue.
It will be available soon with an update of this extension.
Thank you!
