### ISSUE TITLE
Change ctrl+alt access to  vscode-kb-macro ?

### ISSUE THREAD

**Issue by mcmassociates** [tshino/vscode-kb-macro#230]
I am physically unable ton press Ctrl and Alt together ( admin@mcmassociates.io )  -- David

**Comment by tshino** [comment]
Thank you for your question!
If I understand correctly, you are not able to use the keyboard shortcuts `Ctrl+Alt+R` and `Ctrl+Alt+P`, and want to change them to other key combinations that you can use.
Yes, you can change the shortcuts.
1. Open Keyboard Shortcuts on your VS Code.
2. Search for `"ctrl+alt+r"`, then you will find the two commands: `Keyboard Macro: Start Recording` and `Keyboard Macro: Finish Recording`.
3. Right-click on each line and select `Change Keybinding...` to change the key combination.
4. If you have successfully changed the `ctrl+alt+r` to another key, do the same thing for `"ctrl+alt+p"`.

**Comment by mcmassociates** [comment]
Thank you, tshino! Finally found this video which answers my question: 

https://www.youtube.com/watch?v=kI2idVmblMw 

Otherwise, I was going to have my toes or popsickle sticks! -- David 

On 2023-04-04 10:48, tshino wrote:

> Thank you for your question!
> If I understand correctly, you are not able to use the keyboard shortcuts Ctrl+Alt+R and Ctrl+Alt+P, and want to change them to other key combinations that you can use.
> Yes, you can change the shortcuts. 
> 
> * Open Keyboard Shortcuts on your VS Code.
> * Search for "ctrl+alt+r", then you will find the two commands: Keyboard Macro: Start Recording and Keyboard Macro: Finish Recording.
> * Right-click on each line and select Change Keybinding... to change the key combination.
> * If you have successfully changed the ctrl+alt+r to another key, do the same thing for "ctrl+alt+p".
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/tshino/vscode-kb-macro/issues/230#issuecomment-1496213204
[2]

**Comment by tshino** [comment]
You are welcome! Glad to hear that.

**Comment by mcmassociates** [comment]
Thought you might enjoy seeing the tutorial I wrote for my tech-writing
students at Austin Community College (Austin, Texas): 

https://mcmassociates.io/vsc_course/vsc_changekeybindings.html 

Prefer to show your full name, location? -- David 

On 2023-04-05 05:14, tshino wrote:

> You are welcome! Glad to hear that. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/tshino/vscode-kb-macro/issues/230#issuecomment-1497247088
[2]
