### ISSUE TITLE
Feature-Request: Start and Repeat Makro until end of document 

### ISSUE THREAD

**Issue by trx222** [tshino/vscode-kb-macro#34]
Hi and thank you for your work on this plugin. I waited long time for it ;)

Now comes the wishes: I often record a macro to manipulate imports an scripts - the I have to replay a makro für every line, so I also record the "cursor down to next line". It would be great of I can replay the makro until the end on document with an extra shortcut. 

Maybe with some savety checks the the makro knows if it will not reach the end and escape then.

best regards

**Comment by tshino** [comment]
Thank you for your request! I'm very happy to hear a request like this.

I would like to try to implement this feature.
I think some text editor has the same feature, but I don't know the editor's name.
If you know, could you please tell me the names of such text editors?
And if they are included in the [keymap wrappers](https://github.com/tshino/vscode-kb-macro/blob/main/keymap-wrapper/README.md), I will assign the original keybindings for the new command for those editors.

Also, I think if I could know some information about the existing editor's feature and/or test its behavior, it will help me to design the feature and especially the safety logic you mentioned.
Anyway, I think I can implement it.

Thanks.

**Comment by tshino** [comment]
Thank you for the info and for offering to check my code!

And now, I'm very happy to know the fact that a mac user is using this extension. That means this extension is working on mac. In fact, I have never tested it on mac myself, though the automated test on CI is running on Windows, Linux, and macOS as well.
😁

**Comment by trx222** [comment]
It works great for me 👍🏼

**Comment by tshino** [comment]
Hi @trx222, I have just implemented the feature and created a Pull Request.
If you have time, could you take a look at that perhaps at least the description?

If you want to try it your own, the steps would be: (I don't know much about mac though)
- clone this repo and checkout the branch of the PR
- `npm install`
- launch vscode (`code .`)
- in the `Run and Debug`, select `Run Extension`, and run it.

Any comments or requests are welcome.
Thanks.

**Comment by trx222** [comment]
Hi @tshino  - cool, I will try it tomorrow!

**Comment by trx222** [comment]
Can you guide me how I can test the new command then ?  I have it running but have no shortcut for the new command ...

**Comment by tshino** [comment]
Yes. The new command doesn't have a shortcut yet. You should use Command Palette and search like 'macro repeat til'.
What key would you recommend to assign to the command as default?

**Comment by trx222** [comment]
Ok, I checked the keymap editor and didn't found the new one. 
I am relative new to vsc ( because the missing macro functionality :-D ) so I don't know if I can say which keymap is good and not already used to something important. If possible I would recommend to use an additional modifier key to replay like SHIFT+CTRL+ALT+P

**Comment by tshino** [comment]
Let's see step by step.

If you have successfully cloned the repo and checked out the branch, you should find some new files like `src/end_of_file_detector.js`.
![image](https://user-images.githubusercontent.com/732920/149938068-8aaf6ca3-9072-42df-a8e5-10b219a298a1.png)

If you have successfully run the extension, another vscode instance will be launched, and **on the new vscode instance** you should be able to find the new command named `Keyboard Macro: Repeat Playback Till End of File`.
![image](https://user-images.githubusercontent.com/732920/149937863-ad5eb8db-ef15-492b-ad4f-c9cbf1bb6c2f.png)

You can find the new command both in Command Palette (cmd+shift+p) and in Keyboard Shortcuts (cmd+k cmd+s).
![image](https://user-images.githubusercontent.com/732920/149936491-64faae87-77ae-4220-8d9d-36f0f40b636f.png)
![image](https://user-images.githubusercontent.com/732920/149936579-270a6485-fb89-4196-a5d8-1b055118b632.png)

**Comment by tshino** [comment]
Since it works for me, now I will merge the pull request.
And I start to prepare for the next release.

**Comment by tshino** [comment]
I have published [v0.10.0](https://github.com/tshino/vscode-kb-macro/releases/tag/v0.10.0) which includes this feature.
The new command is available at Command Palette (Ctrl+Shift+P or Cmd+Shift+P for mac).

It doesn't have a default keyboard shortcut, but I think it is not so big a problem.
Users can assign it to an arbitrary keystroke.
Since this extension may be used by users with a variety of different keymaps, adding a new shortcut key may cause conflicts possibly for some users. So I think we should keep default keyboard shortcuts as fewest as possible.

Again, thank you for your request for this great new feature!
