### ISSUE TITLE
Saving a macro and assigning a keyboard shortcut to it

### ISSUE THREAD

**Issue by mahadea** [tshino/vscode-kb-macro#386]
So, I can use Ctrl-Alt-R and record a macro and Ctrl-Alt-P to play it back right away. But I need to "save" the macro and replay it later. I need to create many such macros.
Ideally I would like to able to assign keyboard shortcuts to these macros, but I can live with going to a menu option and clicking too.

I looked thru the documentation and couldn't figure out how to do it.  Am I missing something obvious?
thanks

**Comment by tshino** [comment]
@mahadea Thank you for asking! You can save the macro.

The command `Keyboard Macro: Copy Macro as Keybinding` is exactly for that purpose.
After recording a macro, you can use the command to get the macro definition as JSON text and paste it into your keybinding.json file to assign keyboard shortcuts to the macro.
Please find the section [How to save the recorded sequence for future use](https://github.com/tshino/vscode-kb-macro#how-to-save-the-recorded-sequence-for-future-use) in the README.md.

Thank you.

**Comment by mahadea** [comment]
I suffered from tl;dr syndrome, mea culpa. Thanks for pointing it out. I like that I can go back and tweak the json as well!
