### ISSUE TITLE
Feature-Request: Save macros so that they can be run later

### ISSUE THREAD

**Issue by UrmaGurd** [tshino/vscode-kb-macro#40]
As far as I can see this is a record one, use many design.

I want to save my macro keystroke sequence, with a name, so that it can be run later (even given a keyboard shortcut) so that I can record many macros and run them when needed.

**Comment by tshino** [comment]
Thank you for the request!
I agree on the usefulness of saving macros, although I'm not familiar with using such a feature.

My current plan is as follows.
1. Add a new command to create a JSON text that contains the latest recorded sequence.
    - The JSON text is in the keybindings format of vscode, so you can copy-and-paste it to `keybindings.json` with any key.
    - The keybinding invokes the `kb-macro.playback` command with the recorded sequence in the `args` parameter.
2. Add `sequence` argument support to the `kb-macro.playback` command.

Maybe, the JSON text would look like this:
```
{
  "key": "",
  "command": "kb-macro.playback",
  "args": {
    "sequence": [
      { "command": "xxxx" },
      { "command": "yyyy", "args": "zzz" }
    ]
  }
}
```

**Comment by UrmaGurd** [comment]
Just being able to save the sequence and playback between VS Code sessions would be useful (does it do that now? If so, I've missed it in the docs)

With the JSON format, being able to edit the command sequence.

**Comment by tshino** [comment]
> (does it do that now? If so, I've missed it in the docs)

No. Currently, the recorded sequence is being kept only in the memory and discarded before every new recording.
So, this feature will open a new door. 😊

**Comment by UrmaGurd** [comment]
Ah, perfect, saving the sequence to disk will be really useful and as you say open up up many possibilities.

**Comment by tshino** [comment]
Hi @UrmaGurd,

I have implemented two fundamental functionalities.
And I think it is worth making a new release!

The two functionalities are retrieving the recorded macro as JSON and playback of a macro specified by JSON.

The user is needed to paste the JSON to their own `keybindings.json` file manually.
So I mean saving macros to disk is not included in this feature actually. But I think it's enough.

If there's no problem, I will make a release with this feature soon.
Thanks!

**Comment by UrmaGurd** [comment]
Sounds great.

**Comment by UrmaGurd** [comment]
I saw the release yesterday, does it include this change? If so, how does it work?

**Comment by UrmaGurd** [comment]
Brilliant! Just need to get VS Code to update to new version now.

    On Monday, 7 February 2022, 15:35:55 GMT, tshino ***@***.***> wrote:  
 
 


If you are seeing v0.11.0, yes.
I wrote an explanation in the README. Please check out the How to save the recorded sequence for future use section.
